baseurl: "/"
title: "Maksym Koval"
languageCode: "en-us"
theme: "hyde"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - Name: "About"
      URL: "https://srcmaxim.com/about/"
    - Name: "Github"
      URL: "https://github.com/srcmaxim/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/maksim-koval/"

params:
  description: "blog about Java, AWS, Quarkus, GraalVM and DynamoDB"

disqusShortname: srcmaxim-com
googleAnalytics: 208884731
